In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

# Answer1:
list_ is a list of objects and array_list is a array of list.

In [3]:
type(array_list)

numpy.ndarray

In [4]:
type(list_)

list

# Answer2:

In [13]:
def func(a):
    for i in a:
        return type(i)
func(list_)

str

In [10]:
func(array_list)

numpy.str_

# Answer3:

In [16]:
arra_list = np.array(object = list_, dtype = int)
arra_list

array([1, 2, 3, 4, 5])

Yes the elements in arra_list and list_ are of different datatypes.

In [18]:
def fun(a):
    for i in a:
        return type(i)
fun(arra_list)

numpy.int64

In [19]:
fun(list_)

str

In [20]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

# Answer4:

In [21]:
np.size(num_array)

6

In [22]:
np.shape(num_array)

(2, 3)

# Answer5:

In [24]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Answer6:

In [25]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])